### ISSUE TITLE
Does not start on wayland

### ISSUE THREAD

**Issue by ppd** [ppd1990/uconfig-snap#1]
```
This application failed to start because it could not find or load the Qt platform plugin "wayland-egl"
in "".

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

Reinstalling the application may fix this problem.
Aborted (core dumped)
```

**Comment by sebcaux** [comment]
Can you please give me details about that?
Qt version, platform, OS version, compile options...

**Comment by ppd** [comment]
I'm very sure it is just the missing qtwayland5 platform plugin that is not included in the snap.
I am on the road atm, but as soon as I'm back I'll test on wayland with the correct platform plugin included.

For reference:
The snaps are compiled on the "core18" base of the snap ecosystem, which in turn is based on "core" (I believe). This essentially boils down to an extremely slimmed down version of Ubuntu 18.04[...].

I'll ping you back if that does not work out. Thanks for helping out :+1:

**Comment by ppd** [comment]
qtwayland5 does indeed fix the problem. Pure snapped Wayland Qt looks very rough in Ubuntu though as it does not pick up the system theme.

Options:
- Run with DISABLE_WAYLAND=1, so via XWayland 
- Figure out the theming (qt5-gtk-platformtheme)

**Comment by ppd** [comment]
Current revision starts and looks ok.
Some theme issues remain without DISABLE_WAYLAND. I'll investigate this further and consider this issue resolved.

For reference:
https://forum.snapcraft.io/t/qt-apps-and-gtk-themes-an-investigation-with-partial-success/10513/9
